version: '3.6'
services:

  pyback:
    image: pyback:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: pyback01
    env_file:
    - example.env
    - pyback.env
    volumes:
    - ../src:/src
    ports:
    - 8000:8000
    depends_on:
    - db


  pybot:
    image: pybot:latest
    container_name: pybot01
    env_file:
    - example.env
    - pybot.env
    ports:
    - 5000:5000

  db:
    image: postgres:10.1-alpine
    container_name: pg01
    ports:
    - 5432:5432
    volumes:
    - postgres_data:/var/lib/postgresql/data/


  ngrok:
    image: wernight/ngrok:latest
    env_file:
    - example.env
    - ngrok.env
    environment:
    - NGROK_PORT=pybot:5000
    ports:
    - 4040:4040


volumes:
  postgres_data: